Use mprofiel instead of mprofiel-admin
jsebrech/contact-picker-service-nodejs pull request #4
Opened 2020-08-11 09:29 UTC by vademo

- ACCOSMOTNG-117
    - rename
    - update type
    - update tests
    - set publish config to default (registry.npmjs.org)

2020-08-12 07:44 UTC, jsebrech requested changes
graag ook nog een changelog blokje aan de readme toevoegen, aangezien dit een breaking change is en dus een 2.0.0 versie zal noodzakelijk maken

2020-08-12 07:44 UTC, jsebrech commented on README.md
> +* Create a service account with read permissions on the mprofiel service.
iets te summier? misschien zeggen welk recht de service account specifiek moet hebben?

2020-08-12 07:44 UTC, jsebrech commented on src/mprofiel/service.ts
> +        const searchLastName =
lijkt me dat je die 2 calls kan vervangen door 1 call met qs parameter "search", niet?

2020-08-13 07:54 UTC, vademo commented on src/mprofiel/service.ts
> +        const searchLastName =
klopt, aangepast

2020-08-13 07:54 UTC, vademo commented on README.md
> +* Create a service account with read permissions on the mprofiel service.
toegevoegd

2020-08-13 07:55 UTC, vademo commented
> graag ook nog een changelog blokje aan de readme toevoegen, aangezien dit een breaking change is en dus een 2.0.0 versie zal noodzakelijk maken

heb een changelog.md file toegevoegd

2020-08-14 12:34 UTC, jsebrech commented on src/mprofiel/service.ts
> +const getFirstWord = (str: string) => (str || '').split(' ')[0];
niet langer nodig?

2020-08-14 12:35 UTC, jsebrech approved these changes
approved, met de opmerking dat er volgens mij nog een lijn dode code in zit

2020-08-14 12:43 UTC, merged